# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and Publish

on:
  #schedule:
  #  - cron: '37 7 * * *'
  push:
    branches: [ "development", "main" ]
    # Publish semver tags as releases.
    #tags: [ 'v*.*.*' ]
  #pull_request:
  #  branches: [ "development", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar

      - name: Copy files
        run: |
          mkdir -p temp
          cp prefixes-minestom/build/libs/prefixes-*-all.jar temp/prefixes-minestom.jar
          cp prefixes-paper/build/libs/prefixes-*-all.jar temp/perfixes-paper.jar
          cp prefixes-spigot/build/libs/prefixes-*-all.jar temp/prefixes-spigot.jar

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: Prefixes-Latest
          path: temp/